# Generated by Django 6.0 on 2026-01-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist_app", "0002_tasklist_manage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasklist",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
